Remain cursor position and selection in real file
zaucy/vscode-symlink-follow pull request #3
Opened 2022-06-23 12:05 UTC by bzaugt

#### Current problem
Currently, if a user `Ctrl + Click`'s a symbol to go to its definition and the definition is a linked file, the real file will open but at position `0,0`.

#### Fix
With this change, the position will be saved in the linked file and applied again in the real file (including scroll position).

#### Additional info
For this to work, it was necessary to change the `onDidChangeActiveTextEditor` to `onDidChangeTextEditorSelection`, because the cursor selection is not yet set when `onDidChangeActiveTextEditor` is called.

2022-08-26 19:00 UTC, konradsa commented
That seems like a good change. What's the holdup for getting this merged?

2022-08-27 02:42 UTC, zaucy commented
Thanks for your contribution!

> That seems like a good change. What's the holdup for getting this merged?

It got lost in my GitHub notifications. Thanks for the ping!

2022-08-27 04:20 UTC, zaucy requested changes

2022-08-27 04:20 UTC, zaucy commented on src/extension.ts
> +	const disposable = vscode.window.onDidChangeTextEditorSelection(async (selection) => {
Unfortunately switching to `onDidChangeTextEditorSelection` causes the symlink follow dialog to constantly popup when a selection occurs if a user clicks 'cancel'. This also causes this script run a lot more often than I'd like.

Maybe leaving it as `onDidChangeActiveTextEditor` and adding a temporary listener with `onDidChangeTextEditorSelection` to wait for the first emit would work.

Alternatively there might be a way to forward selection in `onDidChangeTextEditorSelection` or some other event through the URI.

2023-03-30 13:49 UTC, neilrubie commented
Really hoping to get this fix!

2023-07-19 15:52 UTC, vient commented
FYI I created copy of this extension with cursor position fixed https://marketplace.visualstudio.com/items?itemName=vient.symlink-follow-2

2023-07-19 18:04 UTC, zaucy commented
If anyone addresses my concerns I'm happy to merge in a fix.

Unfortunately I cannot simply remove the optional dialog since that is an integral part of my workflow.

2023-07-19 18:59 UTC, vient commented
Yeah, I removed optional dialog because it is interfering with History fix and I don't use it anyway. Seems easy to fix tho, ask about following symlink after filtering out "go back" situation.

Somehow I thought that you are not active in this repo, that's why I created new extension instead of making pull requests 😅

2023-07-19 19:50 UTC, zaucy commented
superseded by #6

2023-07-19 19:50 UTC, closed without merging